#https://blog.devgenius.io/dockerizing-spring-app-with-gradle-3b6fbd650bf7
#To use this file, use following command
#gradlew clean build
#docker image build -f Dockerfile_v0 -t sdsani/sds-sb-docker_v0 .

#https://docs.docker.com/engine/reference/commandline/push/
#docker push sdsani/sds-sb-docker_v0:latest
#docker push docker.io/sdsani/sds-sb-docker_v0:latest

#docker run -d -p 8080:8080 --name hello-doc-v0 sdsani/sds-sb-docker_v0

FROM openjdk:11 AS build

#No need for following. Get it done thru docker start command
#EXPOSE 8080

#Security layer
RUN adduser --system --group springboot
USER springboot:springboot

ARG JAR_FILE=/build/libs/*.jar

COPY ${JAR_FILE} app.jar 
ENTRYPOINT ["java","-jar","app.jar"]