FROM openjdk:11 AS build
EXPOSE 8080

RUN addgroup -S springboot && adduser -S springboot -G springboot
USER springboot

VOLUME /tmp
ARG DEPENDENCY=target/dependency
COPY ${DEPENDENCY}/BOOT-INF/lib /app/lib
COPY ${DEPENDENCY}/META-INF /app/META-INF
COPY ${DEPENDENCY}/BOOT-INF/classes /app
ENTRYPOINT ["java","-cp","app:app/lib/*","com.example.hellodocker.HelloDockerApplication"]